name: Generate random user list

on:
  schedule:
    - cron: '0 */12 * * *' # Run this workflow every 12 hours
  workflow_dispatch:

jobs:
  randomize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  

    - name: Run Python code
      run: python generate_client_list.py
    - name: Get current date
      id: date
      run: |
        echo "JOB_DATE=$(date +%Y-%m-%d-%H)" >> $GITHUB_ENV

    - name: "Update commit"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Users generated at: ${{ env.JOB_DATE }}"
        #commit_options: "--amend"
        push_options: "--force"
        skip_fetch: true


