name: Generate random user list

on:
  schedule:
    - cron: '0 */12 * * *' # Run this workflow every 12 hours
  workflow_dispatch:

jobs:
  randomize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  

    - name: Run Python code
      run: python generate_client_list.py
      
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add client_list.json
        git commit -m "Users generated at: $commit_time" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  

